service: carbondryjapan-front

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${opt:profile, "default"}
  stage: ${self:custom.stage}
  region: ap-northeast-1

custom:
  stage: ${opt:stage, "dev"}
  s3Sync:
    - bucketName: ${self:custom.stage}-cdj-front
      localDir: out
plugins:
  - serverless-s3-sync

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-cdj-front
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticSite" }, "/*"]]
